### ISSUE TITLE
[Bug] Integer overflow for torpedo_agro

### ISSUE THREAD

**Issue by floribe2000** [floribe2000/Warships-java-api#1]
## Additional information

Error message:
`com.google.gson.JsonSyntaxException: java.lang.NumberFormatException: Expected an int but was 2256238206 at line 1 column 106396 path $.data..statistics.pvp.torpedo_agro
        at com.google.gson.internal.bind.TypeAdapters$7.read(TypeAdapters.java:228)
        at com.google.gson.internal.bind.TypeAdapters$7.read(TypeAdapters.java:218)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:131)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:222)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:131)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:222)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:131)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:222)
        at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41)
        at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:187)
        at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:145)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:131)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:222)
        at com.google.gson.Gson.fromJson(Gson.java:932)
        at com.google.gson.Gson.fromJson(Gson.java:870)
        at de.floribe2000.warships_java.direct.api.IRequestAction.connect(IRequestAction.java:59)
        at de.floribe2000.warships_java.direct.account.PlayersPersonalDataFullRequest.fetch(PlayersPersonalDataFullRequest.java:163)
        at de.floribe2000.statanalyzer.daily.DailyDatabaseManager.apiQuery(DailyDatabaseManager.java:123)
        at de.floribe2000.statanalyzer.daily.DailyDatabaseManager.lambda$run$0(DailyDatabaseManager.java:192)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:835)
Caused by: java.lang.NumberFormatException: Expected an int but was 2256238206 at line 1 column 106396 path $.data..statistics.pvp.torpedo_agro
        at com.google.gson.stream.JsonReader.nextInt(JsonReader.java:1173)
        at com.google.gson.internal.bind.TypeAdapters$7.read(TypeAdapters.java:226)
        ... 21 more`

**Comment by floribe2000** [comment]
Fixed with version 0.3.0
